[2025-07-29T21:31:18.913+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:31:18.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:31:18.942+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:31:18.938+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:31:29.020+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:31:28.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:31:29.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:31:29.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 10.223 seconds
[2025-07-29T21:31:59.749+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:31:59.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:31:59.775+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:31:59.771+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:32:03.462+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:32:03.423+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:32:03.471+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:32:03.540+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 3.831 seconds
[2025-07-29T21:32:35.690+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:32:35.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:32:35.720+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:32:35.717+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:32:37.735+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:32:37.704+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:32:37.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:32:37.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 2.279 seconds
[2025-07-29T21:33:08.146+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:33:08.149+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:33:08.155+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:33:08.154+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:33:10.458+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:33:10.428+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:33:10.465+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:33:10.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 2.444 seconds
[2025-07-29T21:33:40.985+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:33:40.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:33:40.994+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:33:40.993+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:33:42.103+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:33:42.073+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:33:42.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:33:42.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.242 seconds
[2025-07-29T21:34:12.440+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:34:12.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:34:12.449+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:34:12.448+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:34:13.482+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:34:13.460+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:34:13.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:34:13.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.133 seconds
[2025-07-29T21:34:43.921+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:34:43.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:34:43.932+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:34:43.931+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:34:45.019+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:34:44.992+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:34:45.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:34:45.138+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.251 seconds
[2025-07-29T21:35:15.435+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:35:15.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:35:15.448+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:35:15.446+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:35:16.587+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:35:16.564+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:35:16.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:35:16.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.260 seconds
[2025-07-29T21:35:47.145+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:35:47.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:35:47.154+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:35:47.153+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:35:48.487+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:35:48.462+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:35:48.493+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:35:48.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.425 seconds
[2025-07-29T21:36:19.131+0000] {processor.py:161} INFO - Started process (PID=218) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:36:19.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:36:19.147+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:36:19.144+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:36:20.382+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:36:20.353+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:36:20.390+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:36:20.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.376 seconds
[2025-07-29T21:36:51.017+0000] {processor.py:161} INFO - Started process (PID=224) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:36:51.021+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:36:51.029+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:36:51.027+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:36:52.078+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:36:52.056+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:36:52.084+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:36:52.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.171 seconds
[2025-07-29T21:37:22.372+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:37:22.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:37:22.384+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:37:22.382+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:37:23.426+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:37:23.403+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:37:23.434+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:37:23.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.144 seconds
[2025-07-29T21:37:53.812+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:37:53.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:37:53.820+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:37:53.819+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:37:54.861+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:37:54.831+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:37:54.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:37:54.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.145 seconds
[2025-07-29T21:38:25.464+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:38:25.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:38:25.476+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:38:25.474+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:38:26.493+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:38:26.469+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:38:26.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:38:26.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.139 seconds
[2025-07-29T21:38:56.918+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:38:56.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:38:56.930+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:38:56.928+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:38:58.311+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:38:58.288+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:38:58.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:38:58.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.511 seconds
[2025-07-29T21:39:28.947+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:39:28.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:39:28.959+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:39:28.958+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:39:30.069+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:39:30.038+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:39:30.077+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:39:30.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.263 seconds
[2025-07-29T21:40:00.779+0000] {processor.py:161} INFO - Started process (PID=260) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:40:00.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:40:00.793+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:40:00.788+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:40:01.796+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:40:01.775+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:40:01.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:40:01.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.107 seconds
[2025-07-29T21:40:32.146+0000] {processor.py:161} INFO - Started process (PID=266) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:40:32.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:40:32.160+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:40:32.158+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:40:33.259+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:40:33.240+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:40:33.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:40:33.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.201 seconds
[2025-07-29T21:41:03.805+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:41:03.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:41:03.818+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:41:03.816+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:41:04.857+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:41:04.825+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:41:04.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:41:04.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.169 seconds
[2025-07-29T21:41:35.400+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:41:35.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:41:35.410+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:41:35.409+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:41:36.528+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:41:36.507+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:41:36.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:41:36.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.218 seconds
[2025-07-29T21:42:06.819+0000] {processor.py:161} INFO - Started process (PID=284) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:42:06.823+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:42:06.829+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:42:06.828+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:42:07.938+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:42:07.900+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:42:07.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:42:08.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.253 seconds
[2025-07-29T21:42:38.538+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:42:38.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:42:38.550+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:42:38.548+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:42:39.588+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:42:39.567+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:42:39.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:42:39.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.140 seconds
[2025-07-29T21:43:09.962+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:43:09.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T21:43:09.971+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:43:09.970+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:43:11.096+0000] {logging_mixin.py:188} INFO - [2025-07-29T21:43:11.069+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T21:43:11.103+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T21:43:11.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.225 seconds
[2025-07-29T22:24:14.737+0000] {processor.py:161} INFO - Started process (PID=303) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:24:14.798+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:24:14.836+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:24:14.835+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:24:29.867+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:24:29.625+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:24:29.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:24:30.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 15.500 seconds
[2025-07-29T22:25:00.731+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:25:00.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:25:00.772+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:25:00.766+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:25:05.373+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:25:05.335+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:25:05.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:25:05.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 4.940 seconds
[2025-07-29T22:25:36.309+0000] {processor.py:161} INFO - Started process (PID=315) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:25:36.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:25:36.338+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:25:36.335+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:25:38.875+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:25:38.837+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:25:38.885+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:25:39.087+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 2.879 seconds
[2025-07-29T22:26:09.774+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:26:09.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:26:09.795+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:26:09.794+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:26:11.393+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:26:11.361+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:26:11.400+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:26:11.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.800 seconds
[2025-07-29T22:26:42.133+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:26:42.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:26:42.145+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:26:42.143+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:26:43.585+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:26:43.559+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:26:43.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:26:43.809+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.704 seconds
[2025-07-29T22:27:14.527+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:27:14.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:27:14.566+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:27:14.564+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:27:15.847+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:27:15.811+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:27:15.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:27:15.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.433 seconds
[2025-07-29T22:27:46.131+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:27:46.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:27:46.141+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:27:46.140+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:27:47.623+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:27:47.589+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:27:47.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:27:47.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.609 seconds
[2025-07-29T22:28:17.897+0000] {processor.py:161} INFO - Started process (PID=345) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:28:17.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:28:17.906+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:28:17.905+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:28:18.950+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:28:18.910+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:28:18.958+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:28:19.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.163 seconds
[2025-07-29T22:28:49.345+0000] {processor.py:161} INFO - Started process (PID=351) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:28:49.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:28:49.359+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:28:49.357+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:28:50.739+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:28:50.704+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:28:50.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:28:50.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.497 seconds
[2025-07-29T22:29:21.379+0000] {processor.py:161} INFO - Started process (PID=357) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:29:21.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:29:21.387+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:29:21.386+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:29:22.670+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:29:22.645+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:29:22.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:29:22.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.378 seconds
[2025-07-29T22:29:52.912+0000] {processor.py:161} INFO - Started process (PID=363) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:29:52.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:29:52.924+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:29:52.922+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:29:54.785+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:29:54.763+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:29:54.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:29:54.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.986 seconds
[2025-07-29T22:30:25.711+0000] {processor.py:161} INFO - Started process (PID=369) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:30:25.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:30:25.721+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:30:25.720+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:30:26.923+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:30:26.888+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:30:26.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:30:27.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.326 seconds
[2025-07-29T22:30:57.645+0000] {processor.py:161} INFO - Started process (PID=375) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:30:57.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:30:57.656+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:30:57.654+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:30:58.850+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:30:58.820+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:30:58.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:30:59.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.402 seconds
[2025-07-29T22:31:29.660+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:31:29.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:31:29.673+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:31:29.671+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:31:30.983+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:31:30.960+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:31:30.990+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:31:31.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.444 seconds
[2025-07-29T22:32:01.743+0000] {processor.py:161} INFO - Started process (PID=387) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:32:01.747+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:32:01.753+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:32:01.752+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:32:04.138+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:32:04.110+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:32:04.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:32:04.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 2.529 seconds
[2025-07-29T22:32:34.683+0000] {processor.py:161} INFO - Started process (PID=393) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:32:34.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:32:34.698+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:32:34.696+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:32:35.914+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:32:35.887+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:32:35.921+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:32:35.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.346 seconds
[2025-07-29T22:33:06.259+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:33:06.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:33:06.269+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:33:06.268+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:33:07.486+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:33:07.460+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:33:07.492+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:33:07.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.325 seconds
[2025-07-29T22:33:38.222+0000] {processor.py:161} INFO - Started process (PID=405) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:33:38.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:33:38.235+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:33:38.231+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:33:39.907+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:33:39.881+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:33:39.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:33:39.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.780 seconds
[2025-07-29T22:34:10.745+0000] {processor.py:161} INFO - Started process (PID=411) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:34:10.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:34:10.759+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:34:10.757+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:34:11.961+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:34:11.937+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:34:11.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:34:12.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.301 seconds
[2025-07-29T22:34:42.227+0000] {processor.py:161} INFO - Started process (PID=417) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:34:42.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:34:42.238+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:34:42.236+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:34:43.645+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:34:43.601+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:34:43.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:34:43.790+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.585 seconds
[2025-07-29T22:35:14.135+0000] {processor.py:161} INFO - Started process (PID=423) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:35:14.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:35:14.146+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:35:14.145+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:35:15.340+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:35:15.313+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:35:15.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:35:15.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.311 seconds
[2025-07-29T22:35:45.926+0000] {processor.py:161} INFO - Started process (PID=429) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:35:45.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:35:45.937+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:35:45.936+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:35:47.187+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:35:47.164+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:35:47.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:35:47.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.372 seconds
[2025-07-29T22:36:17.843+0000] {processor.py:161} INFO - Started process (PID=435) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:36:17.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:36:17.853+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:36:17.852+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:36:18.978+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:36:18.956+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:36:18.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:36:19.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.226 seconds
[2025-07-29T22:36:49.279+0000] {processor.py:161} INFO - Started process (PID=441) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:36:49.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:36:49.296+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:36:49.294+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:36:50.546+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:36:50.523+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:36:50.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:36:50.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.378 seconds
[2025-07-29T22:40:59.740+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:40:59.745+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:40:59.752+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:40:59.751+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:41:06.501+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:41:06.480+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:41:06.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:41:06.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 6.902 seconds
[2025-07-29T22:41:36.956+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:41:36.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:41:36.971+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:41:36.969+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:41:39.258+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:41:39.225+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:41:39.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:41:39.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 2.408 seconds
[2025-07-29T22:42:10.331+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:42:10.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:42:10.394+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:42:10.382+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:42:14.503+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:42:14.474+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:42:14.510+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:42:14.607+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 4.388 seconds
[2025-07-29T22:42:45.065+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:42:45.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:42:45.083+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:42:45.080+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:42:47.144+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:42:47.116+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:42:47.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:42:47.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 2.251 seconds
[2025-07-29T22:43:17.595+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:43:17.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:43:17.606+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:43:17.605+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:43:19.051+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:43:19.025+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:43:19.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:43:19.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.687 seconds
[2025-07-29T22:43:50.006+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:43:50.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:43:50.022+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:43:50.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:43:51.507+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:43:51.482+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/pokemon_dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/pokemon_dags.py", line 23, in <module>
    config = ConfigManager(datetime.now())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 14, in __init__
    self.config = self._load_config()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/config_manager.py", line 39, in _load_config
    raise FileNotFoundError(f"No se ha hallado el archivo de configuracion: {self.config_file}")
FileNotFoundError: No se ha hallado el archivo de configuracion: config_file/config.json
[2025-07-29T22:43:51.514+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:43:51.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.621 seconds
[2025-07-29T22:48:06.700+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:48:06.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:48:06.714+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:48:06.712+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:48:12.074+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:48:12.935+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:48:12.934+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:48:12.980+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:48:12.980+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-28 00:00:00+00:00, run_after=2025-07-29 00:00:00+00:00
[2025-07-29T22:48:13.048+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 6.375 seconds
[2025-07-29T22:48:44.003+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:48:44.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:48:44.059+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:48:44.053+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:48:49.985+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:48:50.082+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:48:50.080+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:48:50.149+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:48:50.148+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-28 00:00:00+00:00, run_after=2025-07-29 00:00:00+00:00
[2025-07-29T22:48:50.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 6.386 seconds
[2025-07-29T22:49:20.985+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:49:20.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:49:20.997+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:49:20.995+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:49:22.502+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:49:22.592+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:49:22.590+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:49:22.660+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:49:22.660+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-28 00:00:00+00:00, run_after=2025-07-29 00:00:00+00:00
[2025-07-29T22:49:22.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.777 seconds
[2025-07-29T22:49:53.451+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:49:53.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:49:53.468+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:49:53.465+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:49:55.215+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:49:55.414+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:49:55.413+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:49:55.558+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:49:55.558+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-28 00:00:00+00:00, run_after=2025-07-29 00:00:00+00:00
[2025-07-29T22:49:55.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 2.251 seconds
[2025-07-29T22:50:26.014+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:50:26.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:50:26.028+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:50:26.025+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:50:27.441+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:50:27.527+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:50:27.526+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:50:27.649+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:50:27.648+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-28 00:00:00+00:00, run_after=2025-07-29 00:00:00+00:00
[2025-07-29T22:50:27.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.779 seconds
[2025-07-29T22:50:58.554+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:50:58.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:50:58.564+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:50:58.563+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:50:59.836+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:50:59.913+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:50:59.912+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:50:59.974+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:50:59.973+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-28 00:00:00+00:00, run_after=2025-07-29 00:00:00+00:00
[2025-07-29T22:51:00.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.523 seconds
[2025-07-29T22:51:30.792+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:51:30.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:51:30.847+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:51:30.840+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:51:34.428+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:51:34.717+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:51:34.715+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:51:34.884+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:51:34.882+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:51:35.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 4.626 seconds
[2025-07-29T22:52:05.439+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:52:05.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:52:05.520+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:52:05.516+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:52:07.567+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:52:07.803+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:52:07.800+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:52:08.152+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:52:08.150+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:52:08.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 2.940 seconds
[2025-07-29T22:52:38.912+0000] {processor.py:161} INFO - Started process (PID=224) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:52:38.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:52:38.923+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:52:38.922+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:52:41.100+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:52:41.294+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:52:41.293+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:52:41.492+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:52:41.491+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:52:41.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 2.764 seconds
[2025-07-29T22:53:12.932+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:53:12.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:53:13.118+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:53:13.097+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:53:17.146+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:53:17.270+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:53:17.269+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:53:17.357+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:53:17.354+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:53:17.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 5.052 seconds
[2025-07-29T22:53:48.498+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:53:48.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:53:48.570+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:53:48.566+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:53:50.584+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:53:50.684+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:53:50.683+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:53:50.749+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:53:50.748+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:53:50.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 2.383 seconds
[2025-07-29T22:54:21.558+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:54:21.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:54:21.571+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:54:21.570+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:54:23.153+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:54:23.225+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:54:23.224+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:54:23.291+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:54:23.290+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:54:23.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.842 seconds
[2025-07-29T22:54:54.146+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:54:54.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:54:54.183+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:54:54.180+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:54:55.747+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:54:55.834+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:54:55.833+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:54:55.911+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:54:55.910+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:54:55.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.901 seconds
[2025-07-29T22:55:26.654+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:55:26.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:55:26.665+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:55:26.663+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:55:28.254+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:55:28.565+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:55:28.563+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:55:28.791+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:55:28.790+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:55:28.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 2.245 seconds
[2025-07-29T22:55:59.176+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:55:59.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:55:59.187+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:55:59.186+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:56:00.276+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:56:00.356+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:56:00.355+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:56:00.419+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:56:00.419+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:56:00.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.336 seconds
[2025-07-29T22:56:31.066+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:56:31.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:56:31.076+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:56:31.074+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:56:32.152+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:56:32.264+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:56:32.263+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:56:32.320+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:56:32.319+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:56:32.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.324 seconds
[2025-07-29T22:57:02.696+0000] {processor.py:161} INFO - Started process (PID=304) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:57:02.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:57:02.709+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:57:02.707+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:57:04.412+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:57:04.497+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:57:04.496+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:57:04.562+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:57:04.561+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:57:04.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.952 seconds
[2025-07-29T22:57:35.110+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:57:35.115+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:57:35.126+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:57:35.125+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:57:36.520+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:57:36.628+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:57:36.627+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:57:36.747+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:57:36.747+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:57:36.828+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.743 seconds
[2025-07-29T22:58:07.506+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:58:07.510+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:58:07.517+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:58:07.516+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:58:09.220+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:58:09.315+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:58:09.314+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:58:09.378+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:58:09.377+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:58:09.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.954 seconds
[2025-07-29T22:58:39.929+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:58:39.933+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:58:39.940+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:58:39.939+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:58:41.150+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:58:41.227+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:58:41.226+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:58:41.333+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:58:41.331+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:58:41.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.545 seconds
[2025-07-29T22:59:12.027+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:59:12.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:59:12.036+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:59:12.034+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:59:13.134+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:59:13.209+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:59:13.208+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:59:13.265+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:59:13.264+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:59:13.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.314 seconds
[2025-07-29T22:59:43.918+0000] {processor.py:161} INFO - Started process (PID=334) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:59:43.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T22:59:43.929+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:59:43.927+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:59:45.150+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T22:59:45.226+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:59:45.225+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T22:59:45.283+0000] {logging_mixin.py:188} INFO - [2025-07-29T22:59:45.282+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T22:59:45.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.454 seconds
[2025-07-29T23:00:15.970+0000] {processor.py:161} INFO - Started process (PID=340) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:00:15.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:00:15.981+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:00:15.980+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:00:17.336+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:00:17.403+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:00:17.402+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:00:17.480+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:00:17.479+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:00:17.567+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.621 seconds
[2025-07-29T23:00:47.880+0000] {processor.py:161} INFO - Started process (PID=346) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:00:47.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:00:47.890+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:00:47.889+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:00:49.539+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:00:49.692+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:00:49.690+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:00:49.803+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:00:49.802+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:00:49.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 2.038 seconds
[2025-07-29T23:01:20.291+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:01:20.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:01:20.305+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:01:20.303+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:01:21.514+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:01:21.603+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:01:21.601+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:01:21.674+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:01:21.674+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:01:21.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.475 seconds
[2025-07-29T23:01:52.307+0000] {processor.py:161} INFO - Started process (PID=358) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:01:52.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:01:52.329+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:01:52.327+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:01:53.745+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:01:53.819+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:01:53.818+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:01:53.878+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:01:53.878+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:01:53.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.656 seconds
[2025-07-29T23:02:24.399+0000] {processor.py:161} INFO - Started process (PID=364) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:02:24.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:02:24.411+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:02:24.409+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:02:25.572+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:02:25.676+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:02:25.674+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:02:25.751+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:02:25.751+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:02:25.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.446 seconds
[2025-07-29T23:02:56.427+0000] {processor.py:161} INFO - Started process (PID=370) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:02:56.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:02:56.450+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:02:56.447+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:02:57.472+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:02:57.545+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:02:57.543+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:02:57.604+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:02:57.603+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:02:57.668+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.269 seconds
[2025-07-29T23:03:27.916+0000] {processor.py:161} INFO - Started process (PID=376) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:03:27.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:03:27.932+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:03:27.931+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:03:29.381+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:03:29.452+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:03:29.451+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:03:29.508+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:03:29.507+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:03:29.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.677 seconds
[2025-07-29T23:03:59.781+0000] {processor.py:161} INFO - Started process (PID=382) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:03:59.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:03:59.794+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:03:59.793+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:04:00.831+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:04:00.911+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:04:00.910+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:04:00.972+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:04:00.971+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:04:01.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.303 seconds
[2025-07-29T23:04:31.639+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:04:31.644+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:04:31.655+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:04:31.653+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:04:33.209+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:04:33.317+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:04:33.314+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:04:33.398+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:04:33.397+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:04:33.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.869 seconds
[2025-07-29T23:05:04.196+0000] {processor.py:161} INFO - Started process (PID=394) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:05:04.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:05:04.218+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:05:04.214+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:05:05.842+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:05:05.931+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:05:05.929+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:05:05.992+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:05:05.991+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:05:06.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.920 seconds
[2025-07-29T23:05:36.633+0000] {processor.py:161} INFO - Started process (PID=400) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:05:36.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:05:36.646+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:05:36.644+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:05:37.669+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:05:37.744+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:05:37.743+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:05:37.814+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:05:37.813+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:05:37.885+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.282 seconds
[2025-07-29T23:06:08.107+0000] {processor.py:161} INFO - Started process (PID=406) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:06:08.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:06:08.120+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:06:08.117+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:06:09.625+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:06:09.738+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:06:09.735+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:06:09.822+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:06:09.820+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:06:09.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.822 seconds
[2025-07-29T23:06:40.441+0000] {processor.py:161} INFO - Started process (PID=412) to work on /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:06:40.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/pokemon_dags.py for tasks to queue
[2025-07-29T23:06:40.454+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:06:40.453+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:06:41.760+0000] {processor.py:840} INFO - DAG(s) 'pokemon_etl_dag' retrieved from /opt/airflow/dags/pokemon_dags.py
[2025-07-29T23:06:41.861+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:06:41.860+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-07-29T23:06:41.936+0000] {logging_mixin.py:188} INFO - [2025-07-29T23:06:41.936+0000] {dag.py:3954} INFO - Setting next_dagrun for pokemon_etl_dag to 2025-07-29 00:00:00+00:00, run_after=2025-07-30 00:00:00+00:00
[2025-07-29T23:06:42.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/pokemon_dags.py took 1.588 seconds
